### ISSUE TITLE
Unable to run on ubuntu

### ISSUE THREAD

**Issue by ramakrishnamamidi** [ArtemisMucaj/thefac-extractor#1]
Failed at the zmq@2.15.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zmq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zmq
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zmq
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ramakrishna/.npm/_logs/2017-05-01T12_05_33_023Z-debug.log
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: appdmg@^0.3.2 (node_modules/appdmg):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for appdmg@0.3.10: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN thefac-extractor No repository field.
npm WARN thefac-extractor No license field.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! undefined postinstall: `cd app && npm install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the undefined postinstall script 'cd app && npm install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd app && npm install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

Hi can you help me ewsolve this issue

**Comment by ArtemisMucaj** [comment]
Hi,

Which version of Node.js are you trying to run this on?

I have to warn you this project is no longer maintained, nor feature complete,
which is a nice way of saying it doesn't work!

Thank you for your insterest, I'll update the README for future readers.
